openapi: 3.0.3
info:
  title: Classifier API
  version: 1.0.0
  description: API for accessing EEG classifier data and graph images

paths:
  /api/classifiers:
    get:
      summary: Get all classifiers
      parameters:
        - name: status
          in: query
          schema:
            type: string
        - name: sessionId
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: List of classifiers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Classifier'

  /api/classifiers/{classifierId}:
    get:
      summary: Get a single classifier by ID
      parameters:
        - name: classifierId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Classifier data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Classifier'
        '404':
          description: Classifier not found

  /api/classifiers/{classifierId}/graphs:
    get:
      summary: Get metadata for graphs related to a classifier
      parameters:
        - name: classifierId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of graph metadata
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Graph'
        '404':
          description: Classifier not found

  /api/classifiers/{classifierId}/graphs/{graphName}:
    get:
      summary: Get a specific graph image as PNG
      parameters:
        - name: classifierId
          in: path
          required: true
          schema:
            type: integer
        - name: graphName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: PNG image
          content:
            image/png:
              schema:
                type: string
                format: binary
        '404':
          description: Graph not found

components:
  schemas:
    Classifier:
      type: object
      properties:
        classifierId:
          type: integer
        status:
          type: string
        uploadDate:
          type: string
          format: date-time
        lastUpdated:
          type: string
          format: date-time
        sessionId:
          type: integer
        sessionName:
          type: string
        parameters:
          type: object
          properties:
            a0:
              type: number
              format: float
            a1:
              type: array
              items:
                type: number
                format: float
        graphs:
          type: array
          items:
            $ref: '#/components/schemas/Graph'

    Graph:
      type: object
      properties:
        name:
          type: string
        s3Url:
          type: string
          format: uri
